### ISSUE TITLE
Doc mistake?

### ISSUE THREAD

**Issue by SoundBlaster** [justeat/JustLog#42]
In doc I see:
```Please note that metadata such as filename and line number are unavailable in Objective-C.```
But may be in Swift it is unavailable?
On Objective-C you can do it with:
```NSLog((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__,...```
https://stackoverflow.com/a/969291/602249

**Comment by ghost** [comment]
Hi @SoundBlaster, the problem is that JustLog is a swift library but the Swift macros are of type StaticString, which is unavailable in Objective-C.

Please see this issue for more information: https://github.com/justeat/JustLog/issues/26

Please let us know if you have any other thoughts, otherwise we will close this issue in a few days.

**Comment by SoundBlaster** [comment]
Sorry for this issue. You are 100% right. Closed.
